<?php

namespace addons\mpt\service;

use think\Db;

/**
 * 让宣传片真的能在前台播出来的三件事。
 *
 * ★ 为什么需要这个类 ★
 * 只把 vod_play_from 追加成 aivideo 是不够的，实测有三道关：
 *   1. mac_play_list()（application/common.php:2136）在 $player_info['status'] == '1' 处
 *      把 vodplayer.php 里不存在或未启用的播放组**静默丢掉**，前台连组都看不到；
 *   2. 前台 player.js 按 from 去加载 static/player/{from}.js，没有这个文件播放器起不来；
 *   3. static/js/playerconfig.js 里的 MacPlayerConfig.player_list 是 vodplayer 的缓存副本，
 *      平时由后台 Base::_cache_clear() 重生成；插件补了 vodplayer 却不刷它，前台照样拿不到。
 *
 * 三处都按铁律 4 处理：读 → isset() 判 → 只补缺失 → mac_arr2file()，
 * 站长既有条目一条不动；卸载时也**不删** vodplayer 里的条目（站长可能已手工改过），
 * 只回收插件自己铺的那个播放器 shim 文件。
 */
class PlayerSetup
{
    /** 插件铺的 shim 文件用这行标记，卸载时据此确认是自己的东西才删 */
    const SHIM_MARK = '/* generated by maccms addon: mpt */';

    /** 播放器缓存区文件，站点根相对路径 */
    const PLAYER_CONFIG_JS = 'static/js/playerconfig.js';

    /**
     * 确保 $from 这个播放来源可用。
     * @return array ['code'=>0|1,'msg'=>'']
     */
    public static function ensure($from)
    {
        $from = self::sanitizeFrom($from);
        if ($from === '') {
            return array('code' => 0, 'msg' => lang('mpt/err_bad_play_from'));
        }

        $list = config('vodplayer');
        if (!is_array($list)) {
            $list = array();
        }

        if (isset($list[$from])) {
            // 站长已有同名条目：一个字都不动，只在它被停用时提醒一句
            $status = isset($list[$from]['status']) ? (string) $list[$from]['status'] : '';
            if ($status !== '1') {
                return array('code' => 0, 'msg' => lang('mpt/err_play_from_disabled'));
            }
            // ★ 这里**不无条件**刷 playerconfig.js ★
            // ensure() 是每完成一条任务都会走的路径，无条件刷等于每次出片都去
            // 读—改—写一个核心文件：白费 I/O，还把并发窗口平白撑大。
            // 但也不能完全不管——条目可能是站长手工加进 vodplayer.php 的，
            // 或上一次补写后刷缓存失败了，那样前台永远拿不到这个 from。
            // 折中：先做一次廉价的 strpos 探测，真缺了才去刷。
            self::ensureShim($from);
            self::healPlayerConfigCache($from);

            return array('code' => 1, 'msg' => '');
        }

        // ★ 写 vodplayer.php 必须串行 ★
        // mac_arr2file() 底层是裸 file_put_contents()，没有 LOCK_EX。
        // 补写只发生在「第一次」，但三层推进意味着可能有多个请求同时走到这里，
        // 撞上就会把站长的播放器配置写坏 —— 那是运行期数据，写坏等于全站播放器没了。
        $lockPath = Safety::runtimeFile('vodplayer.lock');
        $lock = @fopen($lockPath, 'c');
        if ($lock === false || !@flock($lock, LOCK_EX)) {
            if ($lock !== false) {
                @fclose($lock);
            }

            return array('code' => 0, 'msg' => lang('mpt/err_write_vodplayer'));
        }
        // ★ 拿到锁后必须重读**文件**，不能再读 config() ★
        // config('vodplayer') 返回的是 App::init() 阶段就载进内存的那份数组，
        // 它不会因为别的进程写了 extra/vodplayer.php 而变化。用它做二次检查，
        // 等锁期间别人的补写永远看不见；更要命的是接着 mac_arr2file() 会把这份
        // 陈旧快照整个写回去，把并发写入（比如站长同时在后台保存播放器管理）
        // 静默回滚掉 —— 那是站长的运行期数据（铁律 4），不能被我们覆盖。
        $list = self::readExtra('vodplayer');
        if (isset($list[$from])) {
            @flock($lock, LOCK_UN);
            @fclose($lock);
            self::ensureShim($from);

            return array('code' => 1, 'msg' => '');
        }

        $list[$from] = array(
            'status' => '1',
            'from' => $from,
            'show' => lang('mpt/player_show'),
            'des' => 'maccms addon: mpt',
            'target' => '_self',
            'ps' => '0',
            'parse' => '',
            'sort' => '1',
            'tip' => '',
            'id' => $from,
        );

        $ok = mac_arr2file(APP_PATH . 'extra/vodplayer.php', $list);

        if ($ok === false) {
            @flock($lock, LOCK_UN);
            @fclose($lock);

            return array('code' => 0, 'msg' => lang('mpt/err_write_vodplayer'));
        }
        // mac_arr2file 只写盘，不动已载入的 Config。不同步的话下面
        // refreshPlayerConfigCache() 读到的还是旧数组，会把 playerconfig.js
        // 重新生成成「没有这个 from」的样子——等于白补。
        Safety::syncConfig('vodplayer', $list);

        // ★ 刷缓存必须还在锁里 ★
        // refreshPlayerConfigCache() 是对核心 static/js/playerconfig.js 的
        // 读—改—写，file_put_contents 也没有 LOCK_EX。放到锁外面的话，两个并发
        // 请求可以交错写同一个文件，把全站播放器配置写坏。
        self::refreshPlayerConfigCache();

        @flock($lock, LOCK_UN);
        @fclose($lock);

        self::ensureShim($from);

        return array('code' => 1, 'msg' => '');
    }

    /**
     * 直接从盘上读一次 application/extra/{$name}.php。
     *
     * ★ 为什么不用 config() ★
     * config() 返回的是 App::init() 阶段载进内存的那份数组，别的进程写了文件
     * 它也不会变。这几个文件都是站长的运行期数据（铁律 4），我们「读 → 合并 →
     * 写回」时必须以盘上的当前内容为准，否则就是拿一份陈旧快照去覆盖别人的修改。
     *
     * 只在持有 runtime/mpt/vodplayer.lock 时调用 —— 三步整体串行，重读才有意义。
     *
     * 走 Safety::includeFresh() 而不是裸 include：opcache 在 revalidate_freq 秒内
     * 不核对 mtime，会把刚被别的进程换掉的文件的旧 opcode 还给我们，锁挡不住这一层。
     */
    protected static function readExtra($name)
    {
        $list = Safety::includeFresh(APP_PATH . 'extra' . DS . $name . '.php');

        return is_array($list) ? $list : array();
    }

    /**
     * 铺 static/player/{from}.js。内容与官方 dplayer.js 等价——同样是一个 iframe 到
     * dplayer.html 的 shim，直链 mp4 用它就够，不需要给插件自带一个播放器。
     */
    public static function ensureShim($from)
    {
        $from = self::sanitizeFrom($from);
        if ($from === '' || $from === 'dplayer' || $from === 'videojs') {
            return true; // 官方已有的播放器不覆盖
        }
        $path = ROOT_PATH . 'static/player/' . $from . '.js';
        if (is_file($path)) {
            return true;
        }
        if (!is_dir(dirname($path))) {
            return false;
        }
        $js = self::SHIM_MARK . "\n"
            . "MacPlayer.Html = '<iframe border=\"0\" src=\"'+maccms.path+'/static/player/dplayer.html\" "
            . "width=\"100%\" height=\"100%\" marginWidth=\"0\" frameSpacing=\"0\" marginHeight=\"0\" "
            . "frameBorder=\"0\" scrolling=\"no\" allowfullscreen=\"true\" allow=\"fullscreen\" vspale=\"0\" noResize></iframe>';\n"
            . "MacPlayer.Show();\n";

        // 原子写：前台播放页随时可能在读这个 shim，覆写到一半会让播放器起不来。
        // 口径与 playerconfig.js、config.php 一致，见 Safety::putFileAtomic()。
        return Safety::putFileAtomic($path, $js);
    }

    /**
     * 这个播放来源还有影片在用吗？
     *
     * ★ 卸载时判它，是为了别把自己刚承诺保留的东西弄坏 ★
     * Mpt::uninstall() 刻意不删两样东西：已写回的成片文件（删了播放组变死链）、
     * extra/vodplayer.php 里的条目（站长运行期数据，铁律 4）。但 shim
     * static/player/{from}.js 与它们是一套的 —— 前台播放页按 from 加载这个文件
     * （核心自带的 dplayer.js / videojs.js 就是同一角色），删掉它，成片在、条目在、
     * 播放组也在，唯独播不出来，等于把"死链"换成了更难排查的"白板播放器"。
     * 所以只有确认没有任何影片还挂着这个 from 时才回收它。
     *
     * @return bool
     */
    public static function fromInUse($from)
    {
        $from = self::sanitizeFrom($from);
        if ($from === '') {
            return false;
        }
        // 转义 LIKE 的通配符：sanitizeFrom() 放行下划线，而它在 LIKE 里是"任意一个字符"，
        // 不转义的话 ai_video 会把 aixvideo 也匹配上。
        $esc = str_replace(array('\\', '%', '_'), array('\\\\', '\%', '\_'), $from);

        // ★ 故意用宽匹配（子串命中就算在用），不去精确切分 $$$ 分隔的 vod_play_from ★
        // 两个方向的判错代价完全不对称：多留一个两百来字节的 shim 文件毫无损失，
        // 少留一个就是站长那些播放组全变白板。宁可误判成"还在用"。
        // 这是一次性动作（只有卸载会调），不在任何热路径上。
        try {
            $hit = Db::name('vod')->where('vod_play_from', 'like', '%' . $esc . '%')->value('vod_id');
        } catch (\Throwable $e) {
            // 查不了就当"还在用"。唯一的调用点是 Mpt::uninstall()，而 Service::uninstall()
            // 会把它抛出的异常原样再抛（Service.php:367-369）—— 为了一个可有可无的清理
            // 让整个卸载失败，代价完全不成比例。
            \think\Log::error('mpt fromInUse: ' . $e->getMessage());

            return true;
        }

        return !empty($hit);
    }

    /**
     * 卸载时回收 shim。只删带本插件标记的文件，站长自己放的同名文件不动。
     *
     * ⚠️ 调用前必须先过 fromInUse()：还有影片挂着这个 from 时删掉它，
     * 那些播放组就再也起不来播放器了。见 fromInUse() 的说明。
     */
    public static function removeShim($from)
    {
        $from = self::sanitizeFrom($from);
        if ($from === '' || $from === 'dplayer' || $from === 'videojs') {
            return;
        }
        $path = ROOT_PATH . 'static/player/' . $from . '.js';
        if (!is_file($path)) {
            return;
        }
        $head = (string) @file_get_contents($path, false, null, 0, 200);
        if (strpos($head, self::SHIM_MARK) !== false) {
            @unlink($path);
        }
    }

    /**
     * playerconfig.js 里没有这个 from 时补刷一次，有就什么都不做。
     *
     * 探测走 strpos（一次读，几十 KB），比无条件重写整个文件便宜得多；
     * 真要重写时同样要拿 ensure() 那把锁，理由见 ensure() 里的说明。
     */
    protected static function healPlayerConfigCache($from)
    {
        $path = self::playerConfigSource();
        if ($path === '') {
            return false;
        }
        $fc = @file_get_contents($path);
        if (!is_string($fc) || strpos($fc, '"' . $from . '":') !== false) {
            return false;
        }

        $lock = @fopen(Safety::runtimeFile('vodplayer.lock'), 'c');
        if ($lock === false || !@flock($lock, LOCK_EX)) {
            if ($lock !== false) {
                @fclose($lock);
            }

            return false;
        }
        $ok = self::refreshPlayerConfigCache();
        @flock($lock, LOCK_UN);
        @fclose($lock);

        return $ok;
    }

    /**
     * 刷新 static/js/playerconfig.js 的缓存区。
     * 逻辑照 application/admin/controller/Base.php::_cache_clear()（那是控制器方法，
     * 需要后台鉴权上下文，插件不便直接调，故在此复制同一段生成逻辑）。
     */
    public static function refreshPlayerConfigCache()
    {
        $src = self::playerConfigSource();
        if ($src === '') {
            return false;
        }
        $fc = @file_get_contents($src);
        if (empty($fc) || !function_exists('mac_get_body')) {
            return false;
        }

        // 站长手工编辑过 vodplayer.php / voddowner.php 时可能缺键，
        // 直接取下标会噼里啪啦报 notice，还可能把 warning 写进正在生成的 js 里。
        $pick = function ($row, array $keys) {
            $out = array();
            foreach ($keys as $key) {
                $out[$key] = isset($row[$key]) ? (string) $row[$key] : '';
            }

            return $out;
        };

        // 三份都从盘上读，理由同 readExtra()：内存里的副本可能落后于文件，
        // 用它重写 playerconfig.js 会把别人刚加的播放器/下载器从缓存区里抹掉。
        // 本方法的两个调用点都持有 runtime/mpt/vodplayer.lock。
        $player = array();
        foreach (self::readExtra('vodplayer') as $k => $v) {
            $player[$k] = $pick($v, array('show', 'des', 'ps', 'parse'));
        }
        $downer = array();
        foreach (self::readExtra('voddowner') as $k => $v) {
            $downer[$k] = $pick($v, array('show', 'des', 'ps', 'parse'));
        }
        $server = array();
        foreach (self::readExtra('vodserver') as $k => $v) {
            $server[$k] = $pick($v, array('show', 'des'));
        }

        $content = 'MacPlayerConfig.player_list=' . json_encode($player)
            . ',MacPlayerConfig.downer_list=' . json_encode($downer)
            . ',MacPlayerConfig.server_list=' . json_encode($server) . ';';

        $jsb = mac_get_body($fc, '//缓存开始', '//缓存结束');
        if ($jsb === '' || $jsb === false) {
            return false;
        }
        $fc = str_replace($jsb, "\r\n" . $content . "\r\n", $fc);

        // 读可能来自 .bak，写永远写回正式文件 —— 口径与核心 Base::_cache_clear() 一致
        // 原子写：这是全站前台每页都要加载的核心缓存文件，撕裂等于整站播放器失灵。
        // 见 Safety::putFileAtomic()。
        return Safety::putFileAtomic(ROOT_PATH . self::PLAYER_CONFIG_JS, $fc);
    }

    /**
     * playerconfig.js 的**读取**来源：正式文件缺失时回落到 .bak。
     *
     * 核心 Base::_cache_clear()（application/admin/controller/Base.php:148-150）就是
     * 这个口径 —— 正式文件被误删过的站点靠 .bak 还能把缓存区重建出来。这里只回落读，
     * 写一律写回正式文件，否则补进去的播放来源会落在一个前台根本不加载的文件里。
     *
     * @return string 绝对路径；两个都不在时返回空串
     */
    protected static function playerConfigSource()
    {
        $path = ROOT_PATH . self::PLAYER_CONFIG_JS;
        if (is_file($path)) {
            return $path;
        }
        $bak = $path . '.bak';

        return is_file($bak) ? $bak : '';
    }

    public static function sanitizeFrom($from)
    {
        $from = strtolower(trim((string) $from));
        if (!preg_match('/^[a-z][a-z0-9_]{1,19}$/', $from)) {
            return '';
        }

        return $from;
    }
}
